### ISSUE TITLE
Phase 1: Zitadel Infrastructure Setup

### ISSUE THREAD

**Issue by oyvindfanebust** [oyvindfanebust/core-poc#21]
## Overview
Set up Zitadel infrastructure components including Docker Compose integration, environment configuration, and database setup to provide authentication services for the banking PoC.

**Part of Epic**: #20 - Implement Zitadel Authentication and Authorization System

### 1.1 Docker Compose Integration
- [ ] Add Zitadel service to existing docker-compose.yml
- [ ] Configure Zitadel with existing PostgreSQL instance (evaluate shared vs dedicated)
- [ ] Set up proper service dependencies and health checks
- [ ] Configure port 8080 for Zitadel (avoiding conflicts with existing services)
- [ ] Use network_mode: host to match existing service pattern

### 1.2 Environment Configuration
- [ ] Add Zitadel-specific variables to .envrc.example:
  ```bash
  # Zitadel Configuration
  ZITADEL_DOMAIN=localhost:8080
  ZITADEL_PORT=8080
  ZITADEL_MASTERKEY=your_32_character_master_key_here
  ZITADEL_EXTERNAL_SECURE=false
  ZITADEL_DATABASE_POSTGRES_HOST=localhost
  ZITADEL_DATABASE_POSTGRES_PORT=5432
  ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
  ZITADEL_DATABASE_POSTGRES_USER=postgres
  ZITADEL_DATABASE_POSTGRES_PASSWORD=postgres
  
  # OIDC Configuration (populated after setup)
  ZITADEL_CLIENT_ID=
  ZITADEL_CLIENT_SECRET=
  ZITADEL_ISSUER_URL=http://localhost:8080
  ZITADEL_JWT_PROFILE_FILE=
  ZITADEL_INTROSPECTION_ENDPOINT=http://localhost:8080/oauth/v2/introspect
  ```

### 1.3 Database Configuration
- [ ] Use existing PostgreSQL instance with separate Zitadel database
- [ ] Configure Zitadel database connection in docker-compose.yml
- [ ] Ensure proper database initialization and migrations
- [ ] Set up database permissions and isolation from banking data

### 1.4 Docker Service Configuration
```yaml
zitadel:
  image: ghcr.io/zitadel/zitadel:latest
  network_mode: host
  depends_on:
    postgres:
      condition: service_healthy
  environment:
    - ZITADEL_DATABASE_POSTGRES_HOST=localhost
    - ZITADEL_DATABASE_POSTGRES_PORT=5432
    - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
    - ZITADEL_DATABASE_POSTGRES_USER=${POSTGRES_USER:-postgres}
    - ZITADEL_DATABASE_POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    - ZITADEL_MASTERKEY=${ZITADEL_MASTERKEY}
    - ZITADEL_EXTERNAL_SECURE=${ZITADEL_EXTERNAL_SECURE:-false}
    - ZITADEL_EXTERNAL_DOMAIN=${ZITADEL_DOMAIN:-localhost}
    - ZITADEL_EXTERNAL_PORT=${ZITADEL_PORT:-8080}
  command: 'start-from-init --masterkey ${ZITADEL_MASTERKEY} --tlsMode disabled'
  healthcheck:
    test: ['CMD', 'curl', '-f', 'http://localhost:8080/debug/ready']
    interval: 10s
    timeout: 5s
    retries: 5
```

## Acceptance Criteria
- [ ] `docker-compose up -d` starts all services including Zitadel
- [ ] Zitadel console is accessible at http://localhost:8080
- [ ] All environment variables are documented in .envrc.example
- [ ] Zitadel database is properly initialized and isolated
- [ ] No port conflicts with existing services (6000-6001: TigerBeetle, 7001-7003: Apps, 5432: PostgreSQL)
- [ ] Services have proper health checks and startup dependencies
- [ ] Zitadel service integrates cleanly with existing infrastructure

## Technical Requirements
- Use official Zitadel Docker image (latest stable)
- Maintain compatibility with existing network_mode: host setup
- Ensure graceful startup/shutdown with other services
- Follow existing Docker Compose patterns in the project
- Share PostgreSQL instance but use separate database

## Integration Points
- Works with existing PostgreSQL service
- Compatible with current port allocation
- Follows existing health check patterns
- Maintains current development workflow

## References
- [Zitadel Docker Compose Setup](https://zitadel.com/docs/self-hosting/deploy/compose)
- [Zitadel Configuration Options](https://zitadel.com/docs/self-hosting/manage/configure)
- Current docker-compose.yml structure in project root
